In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df =pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [5]:
# Q1. Pandas version
pd.__version__

'3.0.5'

In [6]:
# Q2 Records count
df.shape[0]

10000

In [7]:
# Q3 Fuel types
df["fuel_type"].nunique()

3

In [8]:
# Q4 Missing values
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [9]:
# Q5 Max fuel efficiency
df[ (df["origin"] == "Asia") & (df["fuel_efficiency_mpg"]) ].max()

model_year                         2024
origin                             Asia
fuel_type                        Hybrid
drivetrain             Rear-wheel drive
num_doors                             5
engine_displacement                3020
num_cylinders                         8
horsepower                        334.0
vehicle_weight                     5280
acceleration                       23.8
fuel_efficiency_mpg                41.2
dtype: object

In [10]:
# Q6 Median value of horsepower
df["horsepower"].median()


np.float64(254.0)

In [11]:
hp_mode = df["horsepower"].mode()

In [12]:
df["horsepower"].fillna(hp_mode).median()

np.float64(254.0)

In [13]:
# Q7 Sum of Weights

In [17]:
selected = df[df["origin"] == 'Asia'][["vehicle_weight", "model_year"]].head(7)
x = np.array(selected)
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [18]:
XTX = np.dot(x.T, x)
XTX


array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [20]:
XTX_inv = np.linalg.inv(XTX)

In [21]:
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [26]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
w = np.dot(np.dot(XTX_inv, x.T), y)
w

array([0.13644777, 0.2327492 ])

In [27]:
w.sum()

np.float64(0.36919696904925486)